### PR TITLE
Release/v8.2.0

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### This PR fixes a new minor version of MIP 8.2.0:

- See MIPs changelog

### How to test:
**Installation**
- [x] Run mips tests according to MIPs README

**Analysis**
*DNA*
- [x] Run verfication case: justhusky

*RNA*
- [x] Run verfication case: sharpparrot

### Expected outcome:
**Installation**
- [x] Installation, unit and integration tests pass

**Analysis**
*DNA*
- [x] Version_collect should pass without memory errors
- [x] Vcf2cytosure should processes using blacklist
- [x] Analysisrunstatus should pass
- [x] Rtgvcfeval metrics should be consistant with previous MIP release version 8.0.0

*RNA*
- [x] Version_collect should pass without memory errors
- [x] Analysisrunstatus should pass

### Review:
- [x] Code review
- [x] New code is executed and covered by tests
- [x] Tests pass

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
### Expected outcome:
**Installation**
- [x] Installation, unit and integration tests pass

**Analysis**
*DNA*
- [x] Version_collect should pass without memory errors
- [x] Analysisrunstatus should pass
Screenshot 2020-02-10 at 13 32 16

- [x] Vcf2cytosure should processes using blacklist
Screenshot 2020-02-10 at 13 33 36

- [x] Rtgvcfeval metrics should be consistant with previous MIP release version 8.0.0
Screenshot 2020-02-10 at 13 34 18

**Comment by jemten** [comment]
Turns out that Arriba doesn't write the sample names in the report, so no changes are required 🎉 
Will update with RNA output

**Comment by henrikstranneheim** [comment]
👍

**Comment by jemten** [comment]
## RNA
[ ] Installation passes
[ ] Version_collect runs without memory errors
[ ] Analysisrunstatus passes
Screenshot 2020-02-12 at 09 16 02

**Comment by jemten** [comment]
Let's merge and release 🍾

**Pull request merged**
