### PR TITLE
feat(github_actions): Added test of perl install and units tests

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### This PR adds | fixes:

- A replacement for travis CI
- Runs a workflow for a complete MIP install with all tests and coveralls report

### How to test:

- Automatic and continuous test suite

### Expected outcome:
- [ ] Installation, unit and integration test suite pass

### Review:
- [ ] Code review
- [ ] Tests pass

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes. If applicable record manual test results in PR header
- [ ] **MINOR** - when you add functionality in a backwards compatible manner. If applicable record manual test results in PR header
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by jemten** [comment]
Exciting stuff! Let me know when you're ready :)

**Comment by henrikstranneheim** [comment]
@jemten Ready for review! This PR is meant to be a replacement of the travis CI. In the future one can consider doing more parallel jobs like:
- Only running test suite without coveralls so that you do not have to wait for the report
- Critic and tidy and other linters
- There is all sorts of funny actions people are programing and it is quite easy to tailor the triggers and include them I think

**Comment by jemten** [comment]
I'll take a look at the file lib/MIP/Environment/Container.pm coverage drop. Could be related to an error I found in the installation that is addressed in PR #1571

**Comment by henrikstranneheim** [comment]
Great! I Will merge this one so we can get the coveralls and the test automated again and we could consider pausing Travis in a later PR

**Pull request merged**
