### PR TITLE
update vep version from 100 to 103

### PR DESCRIPTION
**Pull request by ramprasadn**
### This PR adds | fixes:

- See above

### How to test:

- Automatic and continuous test suite

### Expected outcome:
- [ ] Installation, unit and integration test suite pass

### Review:
- [x] Code review
- [x] Tests pass

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes. If applicable record manual test results in PR header
- [x] **MINOR** - when you add functionality in a backwards compatible manner. If applicable record manual test results in PR header
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by jemten — COMMENTED** [review]
There looks to be a 103.1 version out. Is that the same as 103?

**Comment by ramprasadn** [comment]
> There looks to be a 103.1 version out. Is that the same as 103?

I noticed that, but docker image for 103.1 was uploaded before 103. That's why I went with 103 :D

**Review by jemten — APPROVED** [review]
I would go with 103.1 docker. If you look at their release tags on the github page, 103.1 is the more recent. https://github.com/Ensembl/ensembl-vep/tags The change seems very minor though :)
Otherwise it looks good 👍

**Comment by ramprasadn** [comment]
> I would go with 103.1 docker. If you look at their release tags on the github page, 103.1 is the more recent. https://github.com/Ensembl/ensembl-vep/tags The change seems very minor though :)
> Otherwise it looks good 👍

I noticed that too. The naming for the dockers images are a bit misleading. There is 103.0 and 103.1, but they were both uploaded before 103. But I guess it makes sense to choose an image that corresponds to the latest github tag. Will go with 103.1 :)

**Pull request merged**
