### PR TITLE
updates chromograph to version 1.1.5

### PR DESCRIPTION
**Pull request by jemten**
### This PR adds | fixes:

- Updates chromograph to version 1.1.5

### How to test:

- Automatic and continuous test suite

### Expected outcome:
- [x] Installation, unit and integration test suite pass

### Review:
- [ ] Code review
- [x] Tests pass

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes. If applicable record manual test results in PR header
- [ ] **MINOR** - when you add functionality in a backwards compatible manner. If applicable record manual test results in PR header
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by jemten** [comment]
Chromograph installs and runs 
```
θ60° 1d [anders.jemt@hasta:~/github_repos/MIP] [S_mip11.0] mip11.0.2* 5s ± perl mip install --singularity_local_install --environment_name S_mip11.0 --select_programs chromograph mip mip_scripts
[INFO] 2022/09/06 13:46:00 MIP_INSTALL - MIP Version: 11.0.2
[INFO] 2022/09/06 13:46:00 MIP_INSTALL - Writing log messages to: /home/anders.jemt/github_repos/MIP/mip_log/2022-09-06/mip_install_2022-09-06T13:46:00.log
[INFO] 2022/09/06 13:46:01 MIP_INSTALL - Installing pipelines: rd_dna rd_rna
[INFO] 2022/09/06 13:46:01 MIP_INSTALL - Installing MIP into environment: S_mip11.0
[INFO] 2022/09/06 13:46:01 MIP_INSTALL - Pulling image: chromograph
[INFO] 2022/09/06 13:46:01 MIP_INSTALL - Saving image to: /home/proj/bin/conda/envs/S_mip11.0/bin/chromograph:1.1.5.sif
[INFO] 2022/09/06 13:47:30 MIP_INSTALL - Pulling image: mip
[INFO] 2022/09/06 13:47:30 MIP_INSTALL - Saving image to: /home/proj/bin/conda/envs/S_mip11.0/bin/mip:v11.0.2.sif
[INFO] 2022/09/06 13:48:26 MIP_INSTALL - Writing container config to: /home/proj/bin/conda/envs/S_mip11.0/bin/templates/mip_container_config.yaml
[INFO] 2022/09/06 13:48:26 MIP_INSTALL - Installing MIP's perl scripts
[INFO] 2022/09/06 13:48:26 MIP_INSTALL - MIP is already installed in the specified conda environment.
[WARN] 2022/09/06 13:48:26 MIP_INSTALL - This will overwrite the current installation of MIP
[INFO] 2022/09/06 13:48:38 MIP_INSTALL - Testing programs in image: chromograph
[WARN] 2022/09/06 13:48:38 MIP_INSTALL - 	No test available for: chromograph
[INFO] 2022/09/06 13:48:38 MIP_INSTALL - Testing programs in image: mip
[INFO] 2022/09/06 13:48:40 MIP_INSTALL - 	Successfully launched: mip 11.0.2
[INFO] 2022/09/06 13:48:40 MIP_INSTALL - Finished installing MIP
1d [anders.jemt@hasta:~/github_repos/MIP] [S_mip11.0] mip11.0.2* 2m52s ± singularity exec  /home/proj/bin/conda/envs/S_mip11.0/bin/chromograph:1.1.5.sif chromograph --version
chromograph 1.1.5
```

**Comment by jemten** [comment]
Run with chromograph completes
```
  #jobid  jobname account partition   alloccpus   TotalCPU    elapsed start   end state   exitcode
  3626194 chromograph_rhoviz_earlycasualcaiman    developme+  core    1   00:15.834   00:00:20    2022-09-06T14:14:16 2022-09-06T14:14:36 COMPLETED   0:0
  3626195 chromograph_rhoviz_hugelymodelbat   developme+  core    1   00:16.103   00:00:20    2022-09-06T14:14:16 2022-09-06T14:14:36 COMPLETED   0:0
  3626196 chromograph_rhoviz_slowlycivilbuck  developme+  core    1   00:15.989   00:00:20    2022-09-06T14:14:16 2022-09-06T14:14:36 COMPLETED   0:0
  3626197 mt_annotation_justhusky developme+  core    1   00:06.421   00:00:13    2022-09-06T14:14:16 2022-09-06T14:14:29 COMPLETED   0:0
```

**Comment by jemten** [comment]
Would appreciate a review on this one @ramprasadn @henrikstranneheim

**Review by henrikstranneheim — APPROVED** [review]
👍

**Comment by henrikstranneheim** [comment]
@jemten There seems to be some github annotations that fail, but they are unrelated to your changes. ignore?

**Pull request merged**
