### PR TITLE
Feature/vep installation update

### PR DESCRIPTION
**Pull request by jemten**
Incorporated your changes to vep installation but the internal vep installation tests still fails for me. I think vep could be an early candidate for container installation on hasta

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
Do not merge this one! I do not feel comfortable with the VEP tests failing. I mailed you another suggestion. I think that one is prefered.

**Comment by jemten** [comment]
Right. Will make make your suggested modifications :)

**Comment by henrikstranneheim** [comment]
According to hasshan the new conda vep build works out of the box, we should check that out

**Comment by hassanfa** [comment]
I was going to open an issue or send an email, but I noticed you have this PR open.

It seems `ensembl-vep` on conda is working just fine. `vep_install` is almost finished building the cache on `Rasta` and it is successfully done on `Hasta`. I'm going to run an annotation tomorrow to see how it is performing.

I've run the following:
```
#https://anaconda.org/bioconda/ensembl-vep=
conda create -n vep -c bioconda -c conda-forge
source activate vep
conda install -c conda-forge -c bioconda ensembl-vep=94.5
cd ~/miniconda2/envs/vep/share/ensembl-vep-94.5-0/
mkdir ~/miniconda2/envs/vep/share/ensembl-vep-cache
./vep_install --CACHEDIR ~/miniconda2/envs/vep/share/ensembl-vep-cache \
--AUTO cf --NO_UPDATE \
--SPECIES homo_sapiens,homo_sapiens_refseq,homo_sapiens_merged -y GRCh37 \
--DESTDIR ~/miniconda2/envs/vep/share/ensembl-vep-94.5-0 --PLUGINS all
```

Also regarding cpanm, the `libgcc-ng` is 8.2.0 on the env, it wasn't `libgcc`.

**Comment by hassanfa** [comment]
Also, regarding `perlbrew`, I found that probably these two variables are the culprit:
`PERL_MM_OPT` and `PERL_MB_OPT`, unsetting them or setting them to conda's perl site_package seems to fix the conflict with `perlbrew` and `vep` installation. You guys most likely know more about this than I do, and I haven't tested it on `hiseq.clinical` though. Just my 2 cents.

**Comment by hassanfa** [comment]
I looked into vep installation without conda env, and the following worked which is minimal installation:

```
conda create -n vep -c bioconda -c conda-forge
source activate vep
conda install -c conda-forge -c bioconda perl=5.26.2
conda install -c conda-forge -c bioconda perl-dbi perl-list-util perl-list-moreutils perl-bio-db-hts perl-try-tiny perl-module-build tabix bcftools
cd ${vep_install_dir}
git clone https://github.com/Ensembl/ensembl-vep.git
cd ensembl-vep/
perl INSTALL.pl --CACHEDIR ${cache_dir} \
--AUTO apcf --NO_UPDATE \
--SPECIES homo_sapiens,homo_sapiens_refseq,homo_sapiens_merged \
-y GRCh37 \
--DESTDIR ./ --PLUGINS all --NO_HTSLIB
```
Above worked on gcc_4.8.5, libgcc_7.2.0, and perl_5.26.2, and I tried it on CentOS 7 and 6 (latest version on both). Make sure you set PERL5LIB to conda's perl sitepackage and ensembl-vep's github clone.

`ensembl-vep` package is working fine, but I thought one might want to install it without conda.

**Comment by jemten** [comment]
I have now tried our original approach and the ones suggested above on Hasta and I get the same "errors". The installation "works" but some VEP tests are failing during the installation. I passes the installation when I install using the conda version, but all the installation tests are skipped so... 
Maybe it is nothing to be concerned with

@hassanfa, did your installation pass the tests?

**Comment by hassanfa** [comment]
Tests are passing for me. But I'm not using Hasta's `.bashrc`, `conda`, nor `perlbrew` installations. I've skipped setup script for new accounts completely.

**Comment by jemten** [comment]
Turned out to be my perl version that messed things up. 5.26.0 works, whereas 5.28.1, 5.26.2 and 5.26.1 doesn't

**Pull request merged**
