### PR TITLE
Feature/test path bed file exists

### PR DESCRIPTION
**Pull request by northwestwitch**
I chose this test because it looked like it was an easy one, but I've spent the whole afternoon on google to understand why it doesn't work.
My idea was to use Perl::Trap to trap the exit signal sent when the file to be tested has the wrong format, but I had no luck. Now I'm curious to see how you would solve the issue :)

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
The trick is that you do not have to test for fail. This is done by the sub itself at runtime. You only have to test that is allows a correct file to pass through and does not fail everything.

**Comment by northwestwitch** [comment]
Ok, I removed the test fail check, but still would have been nice to Trap the exit code. Bah!

**Comment by henrikstranneheim** [comment]
You do not even have to create a temp file, a simple string in to the sub will suffice.

**Comment by northwestwitch** [comment]
Yes, but this way it looked more professional! Do you want me to change it?

**Comment by henrikstranneheim** [comment]
Yes, more professional indeed 😄 !
However,  I think the sub is named improperly it should be: "check_target_file_bed_suffix".
The name check_target_bed_file_exist and give the wrong impression of what the sub really does i.e. that is handles files and not just checks strings.

Could you please rename it and remove the temp file and use a string instead. That would be great.

**Comment by henrikstranneheim** [comment]
Beautiful! 👍

**Pull request merged**
