### PR TITLE
feat(select_file_contigs): Use column one and not header to get conti…

### PR DESCRIPTION
**Pull request by henrikstranneheim**
…g name

- Added new oneliner to get contig names
- Return is lexiographically sorted (for testing predictability purpose), but will be size sorted downstream

### This PR fixes:

- See above

### How to test:

- Automatic and continuous test pass

### Expected outcome:
- Installation, unit and integration tests pass

### Review:
- [ ] Code review
- [ ] New code is executed and covered by tests
- [ ] Tests pass

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
Looks like coveralls agree with you 😄  and so do I. I removed it and also refactored the sub that does the sorting of contigs. I think this is done now. Could you please have a look at the new changes?

**Comment by jemten** [comment]
Great! I think it's almost always the right call to remove code that's no longer in use :)

**Comment by henrikstranneheim** [comment]
Good, I will merge as soon as travis agrees

**Comment by henrikstranneheim** [comment]
@jemten Had to rebase to develop and introduce the rd_dna_panel key in the new sub you made. I hope all the merge conflicts were solved ok and that travis is now happy...

**Comment by jemten** [comment]
Fingers crossed 🤞

**Pull request merged**
