### PR TITLE
feat(telomerecat): Update version

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### This PR adds | fixes:

- See above

### How to test:

- Automatic and continuous test suite

### Expected outcome:
- [ ] Installation, unit and integration test suite pass

### Review:
- [ ] Code review
- [ ] Tests pass

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes. If applicable record manual test results in PR header
- [ ] **MINOR** - when you add functionality in a backwards compatible manner. If applicable record manual test results in PR header
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by jemten — APPROVED** [review]
👍

**Comment by henrikstranneheim** [comment]
Mip install: ✅ 
```
[0|0|523] [henrik.stranneheim@hasta:~/git/MIP] [base] feature/update_telomerecat(3) ± perl mip install --envn D_mip_hs --sp telomerecat
[INFO] 2021/03/26 13:33:04 MIP_INSTALL - MIP Version: v9.1.3
[INFO] 2021/03/26 13:33:04 MIP_INSTALL - Writing log messages to: /home/henrik.stranneheim/git/MIP/mip_log/2021-03-26/mip_install_2021-03-26T13:33:03.log
[INFO] 2021/03/26 13:33:04 MIP_INSTALL - Installing pipelines: rd_dna rd_rna
[INFO] 2021/03/26 13:33:04 MIP_INSTALL - Installing MIP into environment: D_mip_hs
[INFO] 2021/03/26 13:33:04 MIP_INSTALL - Caching image: telomerecat
[INFO] 2021/03/26 13:33:07 MIP_INSTALL - Testing programs in image: telomerecat
[INFO] 2021/03/26 13:33:11 MIP_INSTALL - 	Successfully launched: telomerecat 4.0.0
[INFO] 2021/03/26 13:33:11 MIP_INSTALL - Finished installing MIP
```

Run telomerecat: FAILED
```
Traceback (most recent call last):
  File "parabam/core.pyx", line 61, in parabam.core.CmdLineInterface.handle
  File "/opt/wtsi-cgp/lib/python3.8/site-packages/telomerecat-4.0.0-py3.8.egg/telomerecat/bam2length.py", line 42, in run_cmd
    self.run(
  File "/opt/wtsi-cgp/lib/python3.8/site-packages/telomerecat-4.0.0-py3.8.egg/telomerecat/bam2length.py", line 78, in run
    out_files = telbam_interface.run(input_paths=input_paths, outbam_dir=outbam_dir)
  File "/opt/wtsi-cgp/lib/python3.8/site-packages/telomerecat-4.0.0-py3.8.egg/telomerecat/bam2telbam.py", line 101, in run
    telbam_paths = telbam.process_alignments(outbam_dir, self.total_procs, self.temp_dir, input_paths, reference=reference, verbose=self.verbose)
  File "/opt/wtsi-cgp/lib/python3.8/site-packages/telomerecat-4.0.0-py3.8.egg/telomerecat/telbam.py", line 129, in process_alignments
    with ctx.Pool(processes=parallel_processes) as pool:
  File "/usr/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_forkserver.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 183, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'
/var/spool/slurmd/job1049095/slurm_script: line 54: errorsingularity exec --bind /home/proj/development/rare-disease/references_9.0:/home/proj/development/rare-disease/references_9.0,/home/henrik.stranneheim/develop/justhusky-selected-regions/analysis:/home/henrik.stranneheim/develop/justhusky-selected-regions/analysis,/home/henrik.stranneheim/develop/justhusky-selected-regions/analysis/"$SLURM_JOB_ID":/run/user/$(id -u) docker://quay.io/wtsicgp/telomerecat:4.0.0 telomerecat bam2length --output /home/henrik.stranneheim/develop/justhusky-selected-regions/analysis/justhusky-selected-regions/telomerecat_ar/justhusky-selected-regions_tel.csv -p 12 --temp_dir /home/henrik.stranneheim/develop/justhusky-selected-regions/analysis/$SLURM_JOB_ID /home/henrik.stranneheim/develop/justhusky-selected-regions/analysis/earlycasualcaiman/markduplicates/earlycasualcaiman_lanes_1_sorted_md.bam /home/henrik.stranneheim/develop/justhusky-selected-regions/analysis/hugelymodelbat/markduplicates/hugelymodelbat_lanes_1_sorted_md.bam /home/henrik.stranneheim/develop/justhusky-selected-regions/analysis/slowlycivilbuck/markduplicates/slowlycivilbuck_lanes_1_sorted_md.bam: No such file or directory
```
Reverting and running the same command with `3.4.0` works.

**Comment by henrikstranneheim** [comment]
@dnil Are you still interested of in the output from this or can we turn this off?

**Comment by dnil** [comment]
It is not in use now. The idea is very compelling, and useful both in cancer and a small number of rare disorders. I can take a look at the new version and see if it isn't better, otherwise we can try and prototype around a bit with other similar tools first!

**Comment by dnil** [comment]
This version is more or less on par with the old results wise, but the cram support looks like a must.

I think we will want to support at least one application with this functionality, even if it is only useful in a small number of cases.

This one has publications, so ought to be ok, but so far I have only found two local cases to test with, with different outcome, so I cannot verify it for clinical use. I will see what I can do about arranging more samples. In the meantime I cannot argue strongly either way. Leaving it on makes it slightly easier to just check new suspected cases when they arrive, but honestly I could also just run it manually on demand until we have a verdict. Your call!

**Comment by jemten** [comment]
Seems to work with the new docker build

**Comment by jemten** [comment]
✅ 
image

**Pull request merged**
