### PR TITLE
Feature/check vcf header and keys

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### This PR adds | fixes:

- See below

### How to test:

- Automatic and continuous test suite

### Expected outcome:
- [ ] Installation, unit and integration test suite pass

### Review:
- [ ] Code review
- [ ] Tests pass

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes. If applicable record manual test results in PR header
- [ ] **MINOR** - when you add functionality in a backwards compatible manner. If applicable record manual test results in PR header
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
Now the test are written again:
Screenshot 2020-10-25 at 17 37 19

However, still need to use the .vcf file suffix and not .vcf.gz file suffix

**Comment by henrikstranneheim** [comment]
Now it works:
Screenshot 2020-10-25 at 17 51 37

**Review by jemten — APPROVED** [review]
Great that you got it to work! 
In the future I think that this part of the code deserves a rewrite

**Comment by henrikstranneheim** [comment]
Agreed!

**Pull request merged**
