### PR TITLE
updating glnexus recipe

### PR DESCRIPTION
**Pull request by jemten**
### This PR adds | fixes:

- Changing which file that is normalised in the glnexus recipe for a single sample case. [#1205](https://github.com/Clinical-Genomics/cg/pull/1205)

### How to test:

- Automatic and continuous test suite

### Expected outcome:
- [ ] Installation, unit and integration test suite pass

### Review:
- [ ] Code review
- [ ] Tests pass

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes. If applicable record manual test results in PR header
- [ ] **MINOR** - when you add functionality in a backwards compatible manner. If applicable record manual test results in PR header
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by jemten** [comment]
The analysis test needs to be updated

**Review by henrikstranneheim — DISMISSED** [review]
Looks good so far!

**Review by ramprasadn — APPROVED** [review]
Looks good!

**Comment by jemten** [comment]
For brightcaiman
```
## glnexus input
[0|0|215] θ71° [anders.jemt@hasta:/home/proj/stage/rare-disease/cases] [D_AJ] $ bcftools view -H brightcaiman/analysis/ACC5325A4/deepvariant/ACC5325A4_lanes_1234_sorted_md_deepvar.g.vcf.gz 1:9213634-9213644
1	9213632	.	T	<*>	0	.	END=9213634	GT:GQ:MIN_DP:PL	0/0:21:17:0,21,449
1	9213635	.	A	<*>	0	.	END=9213635	GT:GQ:MIN_DP:PL	0/0:50:17:0,51,509
1	9213636	.	C	<*>	0	.	END=9213636	GT:GQ:MIN_DP:PL	0/0:21:17:0,21,449
1	9213637	.	T	<*>	0	.	END=9213637	GT:GQ:MIN_DP:PL	0/0:50:17:0,51,509
1	9213638	.	AC	A,<*>	0	RefCall	.	GT:GQ:DP:AD:VAF:PL	0/0:33:18:15,3,0:0.166667,0:0,33,54,990,990,990
1	9213640	.	CA	A,C,<*>	55.9	PASS	.	GT:GQ:DP:AD:VAF:PL	1/2:3:19:2,4,13,0:0.210526,0.684211,0:52,33,31,33,0,0,990,990,990,990
1	9213642	.	A	<*>	0	.	END=9213642	GT:GQ:MIN_DP:PL	0/0:27:19:0,27,509
1	9213643	.	A	<*>	0	.	END=9213648	GT:GQ:MIN_DP:PL	0/0:50:18:0,57,569

## glnexus output 
[0|0|226] θ68° [anders.jemt@hasta:/home/proj/stage/rare-disease/cases] [D_AJ] $ bcftools view -H brightcaiman/analysis/brightcaiman/glnexus_merge/brightcaiman_glnex.vcf.gz 1:9213634-9213644
1	9213638	1_9213640_CA_C;1_9213640_CA_A	AC	A	31	.	AF=0.5;AQ=0	GT:DP:AD:GQ:PL:RNC	0/1:19:2,4:3:52,33,31:..
1	9213640	1_9213640_CA_C;1_9213640_CA_A	CA	C	31	.	AF=0.5;AQ=31	GT:DP:AD:GQ:PL:RNC	1/0:19:2,13:3:52,33,0:..
[0|0|215] θ71° [anders.jemt@hasta:/home/proj/stage/rare-disease/cases] [D_AJ] $
```

**Comment by henrikstranneheim** [comment]
@jemten and @ramprasadn What was the impact on single samples for doing this? Are we ready to deploy this?

**Comment by ramprasadn** [comment]
We weren't running glnexus before for single samples because we thought it was redundant as we weren't combining any vcfs. But it looks like besides combining vcfs, glnexus also removes variants tagged as "RefCall" and "Low Qual" (right, Anders?) by deepvariant and these variants seem to be the source of non-unique variants that caused LoqusDB to choke.

Now that we're running glnexus, we shouldn't (I hope) see those anymore.

**Comment by jemten** [comment]
> @jemten and @ramprasadn What was the impact on single samples for doing this? Are we ready to deploy this?

This was the output in MIP 10.0.1
```
[0|0|240] θ69° [henrik.stranneheim@hasta:~] [S_main] 31s 1 $ bcftools view -H /home/proj/stage/housekeeper-bundles/brightcaiman/2021-05-30/brightcaiman_glnex.vcf.gz 1:9213638-9213638
1	9213638	.	AC	A	0	RefCall	.	GT:GQ:DP:AD:VAF:PL	0/0:33:18:15,3:0.166667:0,33,54
1	9213638	.	AC	<*>	0	RefCall	.	GT:GQ:DP:AD:VAF:PL	0/0:33:18:15,0:0:0,990,990
1	9213638	.	AC	A	55.9	PASS	.	GT:GQ:DP:AD:VAF:PL	1/0:3:19:2,4:0.210526:52,33,31
```

**Comment by jemten** [comment]
I think we're ready to deploy.

**Comment by henrikstranneheim** [comment]
This looks great for loqusdb!

**Comment by ramprasadn** [comment]
Results from starfrog, a single sample WGS, are summarised below.

1. Input - GATK combinevariants output
```
Threshold  True-pos-baseline  True-pos-call  False-pos  False-neg  Precision  Sensitivity  F-measure
----------------------------------------------------------------------------------------------------
    1.000            3420095        3433974      26612      12316     0.9923       0.9964     0.9944
     None            3420096        3433975      26681      12315     0.9923       0.9964     0.9943
```

2. Input - Glnexus output
```
Threshold  True-pos-baseline  True-pos-call  False-pos  False-neg  Precision  Sensitivity  F-measure
----------------------------------------------------------------------------------------------------
    3.000            3422912        3437227      15766       9499     0.9954       0.9972     0.9963
     None            3422925        3437245      15794       9486     0.9954       0.9972     0.9963
```

**Review by ramprasadn — APPROVED** [review]
👍🏻

**Pull request merged**
