### PR TITLE
Feature/dna ase

### PR DESCRIPTION
**Pull request by jemten**
### This PR fixes:

- Do ASE analysis on dna vcf

### How to test:

- Automatic and continuous test pass

### Expected outcome:
- Installation, unit and integration tests pass

### Review:
- [ ] Code review
- [ ] New code is executed and covered by tests
- [ ] Tests pass

### CODE REVIEW

**Comment by jemten** [comment]
Testing it out on Hasta right now. Let's see how it turns out before review

**Comment by henrikstranneheim** [comment]
Ready?

**Comment by jemten** [comment]
Turns out Bootstrapann isn't fully compatible with DNA vcf and RNA bam. I have talked to @J35P312 about it and he will take a look

**Comment by henrikstranneheim** [comment]
👍

**Pull request merged**
