### PR TITLE
feat(picard): Update picard to 2.25.0

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### This PR adds | fixes:

- See above

### How to test:

- Automatic and continuous test suite

### Expected outcome:
- [ ] Installation, unit and integration test suite pass

### Review:
- [ ] Code review
- [ ] Tests pass

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes. If applicable record manual test results in PR header
- [ ] **MINOR** - when you add functionality in a backwards compatible manner. If applicable record manual test results in PR header
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
Install: ✅ 
Screenshot 2021-02-26 at 14 50 17

**Comment by henrikstranneheim** [comment]
markdup: ✅ 
```
13:54:18.967 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/picard/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Fri Feb 26 13:54:18 UTC 2021] MarkDuplicates --INPUT /home/henrik.stranneheim/develop/justhusky-selected-regions/analysis/earlycasualcaiman/samtools_merge/earlycasualcaiman_lanes_1_sorted.1.bam --OUTPUT /home/henrik.stranneheim/develop/justhusky-selected-regions/analysis/earlycasualcaiman/markduplicates/earlycasualcaiman_lanes_1_sorted_md.1.bam --METRICS_FILE /home/henrik.stranneheim/develop/justhusky-selected-regions/analysis/earlycasualcaiman/markduplicates/earlycasualcaiman_lanes_1_sorted_md.1.metric --OPTICAL_DUPLICATE_PIXEL_DISTANCE 2500 --CREATE_INDEX true --REFERENCE_SEQUENCE /home/proj/development/rare-disease/references_9.0/grch37_homo_sapiens_-d5-.fasta --MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP 50000 --MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 8000 --SORTING_COLLECTION_SIZE_RATIO 0.25 --TAG_DUPLICATE_SET_MEMBERS false --REMOVE_SEQUENCING_DUPLICATES false --TAGGING_POLICY DontTag --CLEAR_DT true --DUPLEX_UMI false --ADD_PG_TAG_TO_READS true --REMOVE_DUPLICATES false --ASSUME_SORTED false --DUPLICATE_SCORING_STRATEGY SUM_OF_BASE_QUALITIES --PROGRAM_RECORD_ID MarkDuplicates --PROGRAM_GROUP_NAME MarkDuplicates --READ_NAME_REGEX <optimized capture of last three ':' separated fields as numeric values> --MAX_OPTICAL_DUPLICATE_SET_SIZE 300000 --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 5 --MAX_RECORDS_IN_RAM 500000 --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
[Fri Feb 26 13:54:18 UTC 2021] Executing as henrik.stranneheim@compute-0-13.local on Linux 3.10.0-1062.4.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_282-b08; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: Version:2.25.0-SNAPSHOT
INFO    2021-02-26 13:54:19     MarkDuplicates  Start of doWork freeMemory: 2037098392; totalMemory: 2058354688; maxMemory: 5726797824
INFO    2021-02-26 13:54:19     MarkDuplicates  Reading input file and constructing read end information.
INFO    2021-02-26 13:54:19     MarkDuplicates  Will retain up to 20749267 data points before spilling to disk.
INFO    2021-02-26 13:54:19     MarkDuplicates  Read 16422 records. 1 pairs never matched.
INFO    2021-02-26 13:54:20     MarkDuplicates  After buildSortedReadEndLists freeMemory: 1876444688; totalMemory: 2058354688; maxMemory: 5726797824
INFO    2021-02-26 13:54:20     MarkDuplicates  Will retain up to 178962432 duplicate indices before spilling to disk.
INFO    2021-02-26 13:54:21     MarkDuplicates  Traversing read pair information and detecting duplicates.
INFO    2021-02-26 13:54:21     MarkDuplicates  Traversing fragment information and detecting duplicates.
INFO    2021-02-26 13:54:21     MarkDuplicates  Sorting list of duplicate records.
INFO    2021-02-26 13:54:21     MarkDuplicates  After generateDuplicateIndexes freeMemory: 2044730376; totalMemory: 3490185216; maxMemory: 5726797824
INFO    2021-02-26 13:54:21     MarkDuplicates  Marking 567 records as duplicates.
INFO    2021-02-26 13:54:21     MarkDuplicates  Found 222 optical duplicate clusters.
INFO    2021-02-26 13:54:21     MarkDuplicates  Reads are assumed to be ordered by: coordinate
INFO    2021-02-26 13:54:21     MarkDuplicates  Writing complete. Closing input iterator.
INFO    2021-02-26 13:54:21     MarkDuplicates  Duplicate Index cleanup.
INFO    2021-02-26 13:54:21     MarkDuplicates  Getting Memory Stats.
INFO    2021-02-26 13:54:22     MarkDuplicates  Before output close freeMemory: 3475377648; totalMemory: 3490185216; maxMemory: 5726797824
INFO    2021-02-26 13:54:22     MarkDuplicates  Closed outputs. Getting more Memory Stats.
INFO    2021-02-26 13:54:22     MarkDuplicates  After output close freeMemory: 3475594712; totalMemory: 3490185216; maxMemory: 5726797824
[Fri Feb 26 13:54:22 UTC 2021] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 0.05 minutes.
Runtime.totalMemory()=3490185216
```

**Comment by henrikstranneheim** [comment]
Analysis run: ✅ 
```
[[A[0|0|22] [henrik.stranneheim@hasta:~] [base] $ cat develop/justhusky-selected-regions/analysis/mip_log/2021-02-26/mip_2021-02-26T14\:52\:52.log.status
#jobid	jobname	account	partition	alloccpus	TotalCPU	elapsed	start	end	state	exitcode
982248	fastqc_ar_earlycasualcaiman	developme+	core	2	00:24.363	00:00:28	2021-02-26T14:53:45	2021-02-26T14:54:13	COMPLETED	0:0
982249	fastqc_ar_hugelymodelbat	developme+	core	2	00:23.072	00:00:30	2021-02-26T14:53:45	2021-02-26T14:54:15	COMPLETED	0:0
982250	fastqc_ar_slowlycivilbuck	developme+	core	2	00:24.982	00:00:21	2021-02-26T14:53:45	2021-02-26T14:54:06	COMPLETED	0:0
982251	bwa_mem_earlycasualcaiman	developme+	core	36	03:06.378	00:00:20	2021-02-26T14:53:45	2021-02-26T14:54:05	COMPLETED	0:0
982252	bwa_mem_hugelymodelbat	developme+	core	36	02:45.430	00:00:19	2021-02-26T14:53:45	2021-02-26T14:54:04	COMPLETED	0:0
982253	bwa_mem_slowlycivilbuck	developme+	core	36	02:46.783	00:00:17	2021-02-26T14:53:48	2021-02-26T14:54:05	COMPLETED	0:0
982254	samtools_merge_earlycasualcaiman	developme+	core	13	00:08.255	00:00:10	2021-02-26T14:54:05	2021-02-26T14:54:15	COMPLETED	0:0
982255	samtools_merge_hugelymodelbat	developme+	core	13	00:08.057	00:00:10	2021-02-26T14:54:05	2021-02-26T14:54:15	COMPLETED	0:0
982256	samtools_merge_slowlycivilbuck	developme+	core	13	00:07.244	00:00:08	2021-02-26T14:54:05	2021-02-26T14:54:13	COMPLETED	0:0
982257	markduplicates_earlycasualcaiman	developme+	core	32	05:45.911	00:00:54	2021-02-26T14:54:15	2021-02-26T14:55:09	COMPLETED	0:0
982258	markduplicates_hugelymodelbat	developme+	core	32	05:51.668	00:01:00	2021-02-26T14:54:15	2021-02-26T14:55:15	COMPLETED	0:0
982259	markduplicates_slowlycivilbuck	developme+	core	32	05:31.587	00:00:51	2021-02-26T14:54:13	2021-02-26T14:55:04	COMPLETED	0:0
982260	chanjo_sexcheck_earlycasualcaiman	developme+	core	1	00:03.024	00:00:17	2021-02-26T14:55:09	2021-02-26T14:55:26	COMPLETED	0:0
982261	chanjo_sexcheck_hugelymodelbat	developme+	core	1	00:02.943	00:00:08	2021-02-26T14:55:15	2021-02-26T14:55:23	COMPLETED	0:0
982262	chanjo_sexcheck_slowlycivilbuck	developme+	core	1	00:03.094	00:00:22	2021-02-26T14:55:04	2021-02-26T14:55:26	COMPLETED	0:0
982263	samtools_subsample_mt_earlycasualcaiman	developme+	core	1	00:15.936	00:00:26	2021-02-26T14:55:09	2021-02-26T14:55:35	COMPLETED	0:0
982264	samtools_subsample_mt_hugelymodelbat	developme+	core	1	00:15.635	00:00:25	2021-02-26T14:55:15	2021-02-26T14:55:40	COMPLETED	0:0
982265	samtools_subsample_mt_slowlycivilbuck	developme+	core	1	00:15.604	00:00:51	2021-02-26T14:55:04	2021-02-26T14:55:55	COMPLETED	0:0
982266	tiddit_coverage_earlycasualcaiman	developme+	core	1	00:35.801	00:00:43	2021-02-26T14:55:09	2021-02-26T14:55:52	COMPLETED	0:0
982267	tiddit_coverage_hugelymodelbat	developme+	core	1	00:36.439	00:00:43	2021-02-26T14:55:15	2021-02-26T14:55:58	COMPLETED	0:0
982268	tiddit_coverage_slowlycivilbuck	developme+	core	1	00:35.023	00:00:55	2021-02-26T14:55:04	2021-02-26T14:55:59	COMPLETED	0:0
982269	chromograph_cov_earlycasualcaiman	developme+	core	1	00:22.225	00:00:27	2021-02-26T14:55:52	2021-02-26T14:56:19	COMPLETED	0:0
982270	chromograph_cov_hugelymodelbat	developme+	core	1	00:22.122	00:00:26	2021-02-26T14:55:58	2021-02-26T14:56:24	COMPLETED	0:0
982271	chromograph_cov_slowlycivilbuck	developme+	core	1	00:22.238	00:00:26	2021-02-26T14:55:59	2021-02-26T14:56:25	COMPLETED	0:0
982272	sambamba_depth_earlycasualcaiman	developme+	core	2	00:05.308	00:00:15	2021-02-26T14:55:09	2021-02-26T14:55:24	COMPLETED	0:0
982273	sambamba_depth_hugelymodelbat	developme+	core	2	00:03.963	00:00:09	2021-02-26T14:55:15	2021-02-26T14:55:24	COMPLETED	0:0
982274	sambamba_depth_slowlycivilbuck	developme+	core	2	00:04.691	00:00:09	2021-02-26T14:55:04	2021-02-26T14:55:13	COMPLETED	0:0
982275	smncopynumbercaller_justhusky-selected-regions	developme+	core	4	00:08.433	00:00:22	2021-02-26T14:55:15	2021-02-26T14:55:37	COMPLETED	0:0
982276	star_caller_justhusky-selected-regions	developme+	core	4	00:15.188	00:00:23	2021-02-26T14:55:15	2021-02-26T14:55:38	COMPLETED	0:0
982277	telomerecat_ar_justhusky-selected-regions	developme+	core	12	00:40.129	00:04:21	2021-02-26T14:55:15	2021-02-26T14:59:36	COMPLETED	0:0
982278	picardtools_collectmultiplemetrics_earlycasualcai+	developme+	core	2	00:26.185	00:00:31	2021-02-26T14:55:09	2021-02-26T14:55:40	COMPLETED	0:0
982279	picardtools_collectmultiplemetrics_hugelymodelbat	developme+	core	2	00:26.493	00:00:30	2021-02-26T14:55:15	2021-02-26T14:55:45	COMPLETED	0:0
982280	picardtools_collectmultiplemetrics_slowlycivilbuck	developme+	core	2	00:25.522	00:00:28	2021-02-26T14:55:04	2021-02-26T14:55:32	COMPLETED	0:0
982281	picardtools_collecthsmetrics_earlycasualcaiman	developme+	core	2	00:37.877	00:00:40	2021-02-26T14:55:09	2021-02-26T14:55:49	COMPLETED	0:0
982282	picardtools_collecthsmetrics_hugelymodelbat	developme+	core	2	00:38.313	00:00:38	2021-02-26T14:55:15	2021-02-26T14:55:53	COMPLETED	0:0
982283	picardtools_collecthsmetrics_slowlycivilbuck	developme+	core	2	00:37.743	00:00:38	2021-02-26T14:55:04	2021-02-26T14:55:42	COMPLETED	0:0
982284	cnvnator_ar_earlycasualcaiman	developme+	core	13	47:08.527	00:07:49	2021-02-26T14:55:09	2021-02-26T15:02:58	COMPLETED	0:0
982285	cnvnator_ar_hugelymodelbat	developme+	core	13	34:35.189	00:05:19	2021-02-26T14:55:15	2021-02-26T15:00:34	COMPLETED	0:0
982286	cnvnator_ar_slowlycivilbuck	developme+	core	13	44:45.232	00:06:47	2021-02-26T14:55:04	2021-02-26T15:01:51	COMPLETED	0:0
982287	expansionhunter_justhusky-selected-regions	developme+	core	3	00:11.413	00:00:39	2021-02-26T14:55:15	2021-02-26T14:55:54	COMPLETED	0:0
982288	manta_justhusky-selected-regions	developme+	core	36	05:30.709	00:00:42	2021-02-26T14:55:15	2021-02-26T14:55:57	COMPLETED	0:0
982289	tiddit_justhusky-selected-regions	developme+	core	5	01:19:00	00:27:52	2021-02-26T14:55:15	2021-02-26T15:23:07	COMPLETED	0:0
982290	sv_combinevariantcallsets_justhusky-selected-regi+	developme+	core	1	00:06.965	00:00:33	2021-02-26T15:23:07	2021-02-26T15:23:40	COMPLETED	0:0
982291	sv_annotate_justhusky-selected-regions	developme+	core	2	29:23.345	00:17:07	2021-02-26T15:23:40	2021-02-26T15:40:47	COMPLETED	0:0
982292	sv_varianteffectpredictor_justhusky-selected-regi+	developme+	core	25	02:31.827	00:00:36	2021-02-26T15:40:47	2021-02-26T15:41:23	COMPLETED	0:0
982293	sv_vcfparser_justhusky-selected-regions	developme+	core	13	01:25.966	00:00:23	2021-02-26T15:41:24	2021-02-26T15:41:47	COMPLETED	0:0
982294	sv_rankvariant_justhusky-selected-regions	developme+	core	16	00:20.416	00:00:13	2021-02-26T15:41:47	2021-02-26T15:42:00	COMPLETED	0:0
982295	sv_reformat_justhusky-selected-regions	developme+	core	5	00:12.981	00:00:23	2021-02-26T15:42:01	2021-02-26T15:42:24	COMPLETED	0:0
982296	vcf2cytosure_ar_justhusky-selected-regions	developme+	core	4	03:56.362	00:01:51	2021-02-26T15:42:24	2021-02-26T15:44:15	COMPLETED	0:0
982297	deepvariant_earlycasualcaiman	developme+	core	36	09:46:25	00:19:08	2021-02-26T14:55:09	2021-02-26T15:14:17	COMPLETED	0:0
982298	deepvariant_hugelymodelbat	developme+	core	36	09:40:56	00:18:39	2021-02-26T14:55:15	2021-02-26T15:13:54	COMPLETED	0:0
982299	deepvariant_slowlycivilbuck	developme+	core	36	09:50:46	00:19:16	2021-02-26T14:55:04	2021-02-26T15:14:20	COMPLETED	0:0
982300	glnexus_merge_justhusky-selected-regions	developme+	core	30	00:44.621	00:00:17	2021-02-26T15:14:20	2021-02-26T15:14:37	COMPLETED	0:0
982301	gatk_combinevariantcallsets_justhusky-selected-re+	developme+	core	5	00:04.470	00:00:15	2021-02-26T15:14:37	2021-02-26T15:14:52	COMPLETED	0:0
982302	peddy_ar_justhusky-selected-regions	developme+	core	4	00:13.733	00:00:19	2021-02-26T15:14:52	2021-02-26T15:15:11	COMPLETED	0:0
982303	plink_justhusky-selected-regions	developme+	core	2	00:03.991	00:00:13	2021-02-26T15:14:52	2021-02-26T15:15:05	COMPLETED	0:0
982304	gatk_variantevalall_earlycasualcaiman	developme+	core	1	02:31.727	00:02:40	2021-02-26T15:14:52	2021-02-26T15:17:32	COMPLETED	0:0
982305	gatk_variantevalall_hugelymodelbat	developme+	core	1	02:32.530	00:02:40	2021-02-26T15:14:52	2021-02-26T15:17:32	COMPLETED	0:0
982306	gatk_variantevalall_slowlycivilbuck	developme+	core	1	02:28.342	00:02:37	2021-02-26T15:14:52	2021-02-26T15:17:29	COMPLETED	0:0
982307	prepareforvariantannotationblock_justhusky-select+	developme+	core	25	00:21.756	00:00:08	2021-02-26T15:14:52	2021-02-26T15:15:00	COMPLETED	0:0
982308	rhocall_ar_justhusky-selected-regions	developme+	core	13	02:23.638	00:00:22	2021-02-26T15:15:00	2021-02-26T15:15:22	COMPLETED	0:0
982309	vt_ar_justhusky-selected-regions	developme+	core	13	00:25.851	00:00:12	2021-02-26T15:15:22	2021-02-26T15:15:34	COMPLETED	0:0
982310	variant_annotation_justhusky-selected-regions	developme+	core	13	03:18.630	00:00:33	2021-02-26T15:15:35	2021-02-26T15:16:08	COMPLETED	0:0
982311	rhocall_viz_earlycasualcaiman	developme+	core	1	00:08.827	00:00:26	2021-02-26T15:16:08	2021-02-26T15:16:34	COMPLETED	0:0
982312	rhocall_viz_hugelymodelbat	developme+	core	1	00:08.327	00:00:26	2021-02-26T15:16:08	2021-02-26T15:16:34	COMPLETED	0:0
982313	rhocall_viz_slowlycivilbuck	developme+	core	1	00:08.570	00:00:26	2021-02-26T15:16:08	2021-02-26T15:16:34	COMPLETED	0:0
982314	chromograph_rhoviz_earlycasualcaiman	developme+	core	1	00:13.270	00:00:21	2021-02-26T15:16:34	2021-02-26T15:16:55	COMPLETED	0:0
982315	chromograph_rhoviz_hugelymodelbat	developme+	core	1	00:13.980	00:00:23	2021-02-26T15:16:34	2021-02-26T15:16:57	COMPLETED	0:0
982316	chromograph_rhoviz_slowlycivilbuck	developme+	core	1	00:13.390	00:00:21	2021-02-26T15:16:34	2021-02-26T15:16:55	COMPLETED	0:0
982317	upd_ar_hugelymodelbat	developme+	core	1	00:04.573	00:00:16	2021-02-26T15:16:08	2021-02-26T15:16:24	COMPLETED	0:0
982318	chromograph_upd_hugelymodelbat	developme+	core	1	00:11.830	00:00:20	2021-02-26T15:16:24	2021-02-26T15:16:44	COMPLETED	0:0
982319	frequency_filter_justhusky-selected-regions	developme+	core	13	00:22.874	00:00:15	2021-02-26T15:16:08	2021-02-26T15:16:23	COMPLETED	0:0
982320	cadd_ar_justhusky-selected-regions	developme+	core	16	12:46.915	00:02:13	2021-02-26T15:16:24	2021-02-26T15:18:37	COMPLETED	0:0
982321	varianteffectpredictor_justhusky-selected-regions	developme+	core	25	07:56.395	00:01:03	2021-02-26T15:18:37	2021-02-26T15:19:40	COMPLETED	0:0
982322	vcfparser_ar_justhusky-selected-regions	developme+	core	25	00:58.285	00:00:11	2021-02-26T15:19:40	2021-02-26T15:19:51	COMPLETED	0:0
982323	rankvariant_justhusky-selected-regions	developme+	core	36	05:17.633	00:00:26	2021-02-26T15:19:52	2021-02-26T15:20:18	COMPLETED	0:0
982324	endvariantannotationblock_justhusky-selected-regi+	developme+	core	2	00:21.435	00:00:31	2021-02-26T15:20:18	2021-02-26T15:20:49	COMPLETED	0:0
982325	gatk_variantevalexome_earlycasualcaiman	developme+	core	1	02:33.348	00:02:47	2021-02-26T15:20:50	2021-02-26T15:23:37	COMPLETED	0:0
982326	gatk_variantevalexome_hugelymodelbat	developme+	core	1	02:32.891	00:02:46	2021-02-26T15:20:50	2021-02-26T15:23:36	COMPLETED	0:0
982327	gatk_variantevalexome_slowlycivilbuck	developme+	core	1	02:37.770	00:02:50	2021-02-26T15:20:50	2021-02-26T15:23:40	COMPLETED	0:0
982328	qccollect_ar_justhusky-selected-regions	developme+	core	1	00:02.762	00:00:09	2021-02-26T15:44:16	2021-02-26T15:44:25	FAILED	127:0
982329	version_collect_ar_justhusky-selected-regions	developme+	core	1	00:00:00	00:00:00	2021-02-26T15:44:26	2021-02-26T15:44:26	CANCELLED	0:0
982330	multiqc_ar_justhusky-selected-regions	developme+	core	1	00:00:00	00:00:00	2021-02-26T15:44:26	2021-02-26T15:44:26	CANCELLED	0:0
982331	analysisrunstatus_justhusky-selected-regions	developme+	core	1	00:00:00	00:00:00	2021-02-26T15:44:26	2021-02-26T15:44:26	CANCELLED	0:0
```

No picard calls errored and the other errors is just related to teh wrong container being called in the test environment.

**Review by jemten — APPROVED** [review]
What's the status on the new picard command line syntax?

**Comment by henrikstranneheim** [comment]
They do not seem to have made any changes so far, and the "old" syntax that we are using seems to be fully compatible still. A bit surprising, but I guess they would (should) do a major when they stop supporting it

**Pull request merged**
