### PR TITLE
initiate conda

### PR DESCRIPTION
**Pull request by jemten**
### This PR adds | fixes:

- initiate conda

### How to test:

- Automatic and continuous test suite

### Expected outcome:
- [x] Installation, unit and integration test suite pass

### Review:
- [ ] Code review
- [x] Tests pass

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes. If applicable record manual test results in PR header
- [ ] **MINOR** - when you add functionality in a backwards compatible manner. If applicable record manual test results in PR header
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
👍

**Comment by henrikstranneheim** [comment]
I guess this one should not be merged until the updated conda prod is ready?

**Comment by jemten** [comment]
We could probably merge it together with https://github.com/Clinical-Genomics/servers/pull/938
It should work, but we can hold off for a while

**Comment by jemten** [comment]
> We could probably merge it together with [Clinical-Genomics/servers#938](https://github.com/Clinical-Genomics/servers/pull/938) It should work, but we can hold off for a while

Oh I forgot that conda has a new path i that PR. Yeah let's wait a bit

**Comment by henrikstranneheim** [comment]
Will it work with the old conda prod as well i.e. should we patch current prod?

**Comment by henrikstranneheim** [comment]
ok

**Pull request merged**
