### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### This PR adds:

- Ram as code owner

### How to test:

- No code changes

### Expected outcome:
- [ ] Installation, unit and integration test suite pass

### Review:
- [ ] Code review
- [ ] Tests pass

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes. If applicable record manual test results in PR header
- [ ] **MINOR** - when you add functionality in a backwards compatible manner. If applicable record manual test results in PR header
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by jemten — APPROVED** [review]
I approve!

**Comment by henrikstranneheim** [comment]
@ramprasadn Are you fine with being a code owner?

**Comment by ramprasadn** [comment]
Yes! :D  I'm sorry I was sitting on the sidelines on this PR. It just felt strange for me to approve this one as it involved me haha..

**Review by ramprasadn — APPROVED** [review]
👍

**Pull request merged**
