### PR TITLE
Feature/gens installation

### PR DESCRIPTION
**Pull request by raysloks**
### This PR adds | fixes:

- Installation of the gens_preproc container, which contains tabix (as part of htslib) and two perl scripts.
- Post-install test which verifies that the main script is accessible.

### How to test:

- Automatic and continuous test suite

### Expected outcome:
- [ ] Installation, unit and integration test suite pass

### Review:
- [ ] Code review
- [ ] Tests pass

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes. If applicable record manual test results in PR header
- [ ] **MINOR** - when you add functionality in a backwards compatible manner. If applicable record manual test results in PR header
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by jemten — COMMENTED** [review]
Nice work!
Add gens_preproc to these places in the CLI so that one can do selective installations.  https://github.com/Clinical-Genomics/MIP/blob/db2e89fec2674f5c12dbf6ec89eba181433fc742/lib/MIP/Cli/Mip/Install.pm#L143
https://github.com/Clinical-Genomics/MIP/blob/db2e89fec2674f5c12dbf6ec89eba181433fc742/lib/MIP/Cli/Mip/Install.pm#L176

**Comment by raysloks** [comment]
I actually already added it to those places ;)

**Comment by jemten** [comment]
> I actually already added it to those places ;)

Whoops, some sloppy reviewing on my part.

**Review by jemten — APPROVED** [review]
👍

**Pull request merged**
