### PR TITLE
Feature/test io

### PR DESCRIPTION
**Pull request by henrikstranneheim**
…cipes or fastq

### This PR adds | fixes:

- See above

### How to test:

- Automatic and continuous test suite

### Expected outcome:
- [ ] Installation, unit and integration test suite pass

### Review:
- [ ] Code review
- [ ] Tests pass

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes. If applicable record manual test results in PR header
- [ ] **MINOR** - when you add functionality in a backwards compatible manner. If applicable record manual test results in PR header
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
@jemten @ramprasadn Could you give this a code review and see if you think the args and options make sense. If so I will then add this fixture to all analysis recipes in this PR. But I would like to get some feedback before changing them all as there are a few

**Review by jemten — APPROVED** [review]
I like it! Nice to be able to ask for a specific file format. Great work 🥳

**Comment by henrikstranneheim** [comment]
@jemten and @ramprasadn This is ready! The coverage drop is related to Rams previous PR and I will leave it out of this PR. I you do not mind I can merge this as it only affects tests

**Comment by jemten** [comment]
Go ahead 👍

**Comment by ramprasadn** [comment]
This looks great!!

**Comment by henrikstranneheim** [comment]
Great! Thx guys! Merging....

**Pull request merged**
